gen : 1Generator.c
	gcc -Wall -o gen 1Generator.c
	gcc -Wall -o clasT1 12ClassifierTREE.c
	gcc -Wall -o fab1 13FabricBANYAN.c -lm
	gcc -Wall -o schedR1 14SchedulerRR.c
	gcc -Wall -o clasT2 22ClassifierTREE.c
	gcc -Wall -o fab2 23FabricBANYAN.c -lm
	gcc -Wall -o schedR2 24SchedulerRR.c
	gcc -Wall -o clasT3 32ClassifierTREE.c
	gcc -Wall -o fab3 33FabricBANYAN.c -lm
	gcc -Wall -o schedR3 34SchedulerRR.c
	gcc -Wall -o analys3 35Analyser.c
	gcc -Wall -o clasT4 42ClassifierTREE.c
	gcc -Wall -o fab4 43FabricBANYAN.c -lm
	gcc -Wall -o schedR4 44SchedulerRR.c
	gcc -Wall -o analys4 45Analyser.c

clean :
	rm gen clasT1 fab1 schedR1 clasT2 fab2 schedR2 clasT3 fab3 schedR3 analys3 clasT4 fab4 schedR4 analys4