gen : 1Generator.c
	gcc -Wall -o gen 1Generator.c
	gcc -Wall -o clasT1 2ClassifierTREE.c
	gcc -Wall -o clasT2 5ClassifierTREE.c
	gcc -Wall -o fab1 3FabricBANYAN.c -lm
	gcc -Wall -o fab2 6FabricBANYAN.c -lm
	gcc -Wall -o schedR1 4SchedulerRR.c
	gcc -Wall -o schedR2 7SchedulerRR.c
	gcc -Wall -o analys 8Analyser.c

clean :
	rm gen clasT1 clasT2 fab1 fab2 schedR1 schedR2 analys